CREATE ROLE 'doctor_role', 'receptionist_role', 'admin_role', 'patient_role'; 
GRANT SELECT, INSERT, UPDATE ON NHS_Trust_DB.Appointments TO 'doctor_role'; 
GRANT SELECT, INSERT, UPDATE ON NHS_Trust_DB.Prescriptions TO 'doctor_role'; 
GRANT SELECT ON NHS_Trust_DB.Patients TO 'doctor_role'; 
GRANT SELECT ON NHS_Trust_DB.Medications TO 'doctor_role'; 
GRANT SELECT, INSERT, UPDATE ON NHS_Trust_DB.Patients TO 'receptionist_role'; 
GRANT SELECT, INSERT, UPDATE, DELETE ON NHS_Trust_DB.Appointments TO 'receptionist_role'; 
GRANT SELECT ON NHS_Trust_DB.Clinics TO 'receptionist_role'; 
GRANT SELECT ON NHS_Trust_DB.Doctors TO 'receptionist_role'; 
GRANT SELECT (AppointmentID, AppointmentDate, AppointmentTime, ClinicID, PatientID, DoctorID, PhoneOrFace, Status) ON NHS_Trust_DB.Appointments TO 'receptionist_role'; 
GRANT SELECT, INSERT, UPDATE, DELETE ON NHS_Trust_DB.Clinics TO 'admin_role'; 
GRANT SELECT, INSERT, UPDATE, DELETE ON NHS_Trust_DB.Doctors TO 'admin_role'; 
GRANT SELECT, INSERT, UPDATE, DELETE ON NHS_Trust_DB.Medications TO 'admin_role'; 
GRANT SELECT ON NHS_Trust_DB.Patients TO 'admin_role';
GRANT SELECT ON NHS_Trust_DB.Medications TO 'patient_role'; 
FLUSH PRIVILEGES; 
